version: 0.1

phases:
  build:
    commands:
      - gradle --quiet clean build javadoc htmlDependencyReport aws


  post_build:
    commands:
      - aws s3 sync ./tioga-notify-client/build/reports           s3://static.tiogasolutions.org/notify/tioga-notify-client/reports --delete
      - aws s3 sync ./tioga-notify-client/build/docs              s3://static.tiogasolutions.org/notify/tioga-notify-client/docs --delete
      -
      - aws s3 sync ./tioga-notify-engine/build/reports           s3://static.tiogasolutions.org/notify/tioga-notify-engine/reports --delete
      - aws s3 sync ./tioga-notify-engine/build/docs              s3://static.tiogasolutions.org/notify/tioga-notify-engine/docs --delete
      -
      - aws s3 sync ./tioga-notify-jackson/build/reports          s3://static.tiogasolutions.org/notify/tioga-notify-jackson/reports --delete
      - aws s3 sync ./tioga-notify-jackson/build/docs             s3://static.tiogasolutions.org/notify/tioga-notify-jackson/docs --delete
      -
      - aws s3 sync ./tioga-notify-kernel/build/reports           s3://static.tiogasolutions.org/notify/tioga-notify-kernel/reports --delete
      - aws s3 sync ./tioga-notify-kernel/build/docs              s3://static.tiogasolutions.org/notify/tioga-notify-kernel/docs --delete
      -
      - aws s3 sync ./tioga-notify-notifier/build/reports         s3://static.tiogasolutions.org/notify/tioga-notify-notifier/reports --delete
      - aws s3 sync ./tioga-notify-notifier/build/docs            s3://static.tiogasolutions.org/notify/tioga-notify-notifier/docs --delete
      -
      - aws s3 sync ./tioga-notify-processor-logger/build/reports s3://static.tiogasolutions.org/notify/tioga-notify-processor-logger/reports --delete
      - aws s3 sync ./tioga-notify-processor-logger/build/docs    s3://static.tiogasolutions.org/notify/tioga-notify-processor-logger/docs --delete
      -
      - aws s3 sync ./tioga-notify-processor-push/build/reports   s3://static.tiogasolutions.org/notify/tioga-notify-processor-push/reports --delete
      - aws s3 sync ./tioga-notify-processor-push/build/docs      s3://static.tiogasolutions.org/notify/tioga-notify-processor-push/docs --delete
      -
      - aws s3 sync ./tioga-notify-processor-slack/build/reports  s3://static.tiogasolutions.org/notify/tioga-notify-processor-slack/reports --delete
      - aws s3 sync ./tioga-notify-processor-slack/build/docs     s3://static.tiogasolutions.org/notify/tioga-notify-processor-slack/docs --delete
      -
      - aws s3 sync ./tioga-notify-processor-smtp/build/reports   s3://static.tiogasolutions.org/notify/tioga-notify-processor-smtp/reports --delete
      - aws s3 sync ./tioga-notify-processor-smtp/build/docs      s3://static.tiogasolutions.org/notify/tioga-notify-processor-smtp/docs --delete
      -
      - aws s3 sync ./tioga-notify-processor-swing/build/reports  s3://static.tiogasolutions.org/notify/tioga-notify-processor-swing/reports --delete
      - aws s3 sync ./tioga-notify-processor-swing/build/docs     s3://static.tiogasolutions.org/notify/tioga-notify-processor-swing/docs --delete
      -
      - aws s3 sync ./tioga-notify-pub/build/reports              s3://static.tiogasolutions.org/notify/tioga-notify-pub/reports --delete
      - aws s3 sync ./tioga-notify-pub/build/docs                 s3://static.tiogasolutions.org/notify/tioga-notify-pub/docs --delete
      -
      - aws s3 sync ./tioga-notify-sender-couch/build/reports     s3://static.tiogasolutions.org/notify/tioga-notify-sender-couch/reports --delete
      - aws s3 sync ./tioga-notify-sender-couch/build/docs        s3://static.tiogasolutions.org/notify/tioga-notify-sender-couch/docs --delete
      -
      - aws s3 sync ./tioga-notify-sender-http/build/reports      s3://static.tiogasolutions.org/notify/tioga-notify-sender-http/reports --delete
      - aws s3 sync ./tioga-notify-sender-http/build/docs         s3://static.tiogasolutions.org/notify/tioga-notify-sender-http/docs --delete
      -
      - aws s3 sync ./tioga-notify-server-grizzly/build/reports   s3://static.tiogasolutions.org/notify/tioga-notify-server-grizzly/reports --delete
      - aws s3 sync ./tioga-notify-server-grizzly/build/docs      s3://static.tiogasolutions.org/notify/tioga-notify-server-grizzly/docs --delete
      -
      - aws s3 sync ./tioga-notify-test/build/reports             s3://static.tiogasolutions.org/notify/tioga-notify-test/reports --delete
      - aws s3 sync ./tioga-notify-test/build/docs                s3://static.tiogasolutions.org/notify/tioga-notify-test/docs --delete

artifacts:
  discard-paths: yes
  files:
    - tioga-notify-server-grizzly/build/aws/Buildfile
    - tioga-notify-server-grizzly/build/aws/Procfile
    - tioga-notify-server-grizzly/build/distributions/tioga-notify-server-grizzly-*.zip
